port: "amqp://guest:guest@localhost:5672/"
exchange:
  name: "test_exchange"
  type: "direct"
queue_name: "test_queue"
consumer:
  - Consumer1 : "hello.world"
  - Consumer2 : "merry.christmas"
  - Consumer3 : "loopline.systems happy.sad"
...