port: "amqp://guest:guest@localhost:5672/"
exchange:
  name: "test_exchange"
  type: "direct"
queue_name: "test_queue"
consumer:
  - testConsumer1 : "hello.world"
  - testConsumer2 : "hello.christmas"
  - testConsumer3 : "white.christmas"
  - testConsumer4 : "#"
...